# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8abc31c7d0bf9b471531e9bb0b0f23b41405466775678332b2be89f171e8656dfe8f2cda55793b67c95340108cadbef0a979f1811836f31f7bf73f05bd02839b

test:
  secret_key_base: 9a351fd2b6febd53aa3a4457db76a67af2716847e8653378232fa93d35d8261f4a9fee65071484001e8bb82288416977a0bd32c2840a4ddea040e543544b57c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
